
name: Build SimpleElastix

on:
  push:
    # branches:
    #   - develop

jobs:

  job:

    name: Build Linux wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["cp38-cp38"]
        # container: ["quay.io/pypa/manylinux1_x86_64:latest", "quay.io/pypa/manylinux2010_x86_64:latest"]
        
    container: quay.io/pypa/manylinux2010_x86_64:latest

    steps:

      - name: Checkout build scripts
        uses: actions/checkout@v1
        with:
          path: scripts

      #- name: Checkout SimpleElastix
      #  uses: actions/checkout@v1
      #  with:
      #    repository: 'SuperElastix/SimpleElastix'
      #    path: src

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.8
      #
      #- name: Install dependencies
      #  run: pip install wheel twine cmake virtualenv auditwheel

      - name: Build wheel
        run: /__w/SimpleElastix-build/scripts/make_selx.sh ${{ matrix.python_version }}
      
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/hlxpy
      #     publish_branch: docs
